services:
  mariadb:
    image: mariadb:local
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - webnet
    secrets:
      - db_root_password
      - db_password
      - credentials
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$(cat /run/secrets/db_root_password) --silent || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  wordpress:
    image: wordpress:local
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - webnet
    secrets:
      - db_password
      - credentials
    env_file:
      - .env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "nc -z 127.0.0.1 9000 || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 40
      start_period: 60s
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    image: nginx:local
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html:ro
    networks:
      - webnet
    secrets:
      - credentials
    env_file:
      - .env
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy

networks:
  webnet:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/erasahin/data/mariadb
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/erasahin/data/wordpress
      o: bind

secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
